# -*- coding: utf-8 -*-
"""flights_delay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1808FWGpOepnJKxXmZD9Djc_U8xdQwL-j

Γεωργιάνα Πετρίδου ics23143 /
Θεοδώρα Στάμογλου iis22144

# Θέμα 1:Spark RDD ARI

1.
"""

!pip -q install pyspark

!apt-get -qq update
!apt-get -qq install -y openjdk-17-jdk

import os

import time
import numpy as np

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-17-openjdk-amd64"
os.environ["PATH"] += f":{os.environ['JAVA_HOME']}/bin"

from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName("FightDelayAnalytics") \
    .config("spark.sql.shuffle.partitions", "8") \
    .getOrCreate()
sc = spark.sparkContext

lines_rdd = sc.textFile("flights_2000.csv")

flights_rdd = lines_rdd.map(lambda line: line.split(","))

print("Spark session initiated")

"""2."""

header = lines_rdd.first()
data = lines_rdd.filter(lambda line: line != header)

parsed = data.map(lambda line: line.split(","))

def extract_origin_delay(row):
    #ORIGIN_AIRPORT
    origin = row[3]

    #DEP_DELAY
    delay_str = row[6]
    if delay_str == '' or delay_str is None:
       delay = 0.0
    else:
      try:
          delay = float(delay_str)
      except ValueError:
          delay = 0.0

    return (origin,delay)

# Δημιουργούμε το ζεύγος (origin_airport, delay_minutes)
origin_delay = parsed.map(extract_origin_delay)

print("-Pairs(Origin,Delay)-")
for pair in origin_delay.take(5):
    print(pair)

"""3."""

# Μεση καθυστέρηση ανα αεροδρόμιο
def create_comb(v):
    return (v, 1)

def merge_val(acc, v):
    # προσθέτει νέα τιμή σε υπάρχον accumulator
    total_delay = acc[0] + v
    count = acc[1] + 1
    return (total_delay, count)

def merge_comb(acc1, acc2):
    # συγχωνεύει accumulators από διαφορετικά partitions
    total_delay = acc1[0] + acc2[0]
    total_count = acc1[1] + acc2[1]
    return (total_delay, total_count)


execution_times = []
for i in range(5):
    start_time = time.time()  # Ξεκινάει η Μέτρηση χρόνου εκτέλεσης

    avg_rdd = (origin_delay.combineByKey(create_comb, merge_val, merge_comb).mapValues(lambda acc: acc[0] / acc[1]))

    temp_result = avg_rdd.sortBy(lambda x: x[1], ascending=False).take(20)

    end_time = time.time()   # Τελειώνει η Μέτρηση χρόνου εκτέλεσης
    elapsed_time = end_time - start_time
    execution_times.append(elapsed_time)
    print(f"Επανάληψη {i+1}: {elapsed_time:.4f} δευτερόλεπτα")


# Διαδικασία Υπολογισμου του μέσου όρου των 3 (-min, -max) μετρήσεων
times_array = np.array(execution_times)
times_array = np.sort(times_array)
trimmed_times = times_array[1:-1]

avg_rdd_time = np.mean(trimmed_times)

print(f"\nΣύνολο Μετρήσεων: {execution_times}")
print(f"Αφαιρούμενες Τιμές (min/max): {times_array[0]:.4f} / {times_array[-1]:.4f}")
print(f"Μέσος Χρόνος Θέματος 1 (RDD - Trimmed Mean): {avg_rdd_time:.4f} δευτερόλεπτα")

results = avg_rdd.sortBy(lambda x: x[1], ascending=False).collect()
print("\n-Μέση καθυστέρηση ανα αεροδρόμιο-")
for result in results:
    print(f"Airport: {result[0]}, Average Delay: {result[1]:.2f} minutes")

"""4."""

#Top-10 αεροδρόμια με μεγαλύτερη μέση καθυστέρηση
sorted_rdd = avg_rdd.sortBy(lambda x: x[1], ascending=False)
top_10_aipords = sorted_rdd.take(10)
print("-- Top 10 --")
for airport, delay in top_10_aipords:
    print(f"{airport}: {delay:.2f}")

"""# Θέμα 2:Spark DataFrame API

1&2.
"""

df_flights = spark.read.csv("flights_2000.csv",header=True,inferSchema=True)
df_flights.show(5); df_flights.printSchema()

"""3."""

from pyspark.sql.functions import col, avg, desc

df_clean = df_flights.filter(col("CANCELLED") == 0) \
             .na.drop(subset=["DEP_DELAY"])

route_delays = df_clean.groupBy("ORIGIN_AIRPORT", "DEST_AIRPORT") \
                          .agg(avg("DEP_DELAY").alias("AVG_DELAY"))

top_routes = route_delays.orderBy(desc("AVG_DELAY"))


execution_times_routes = []
for i in range(5):
    start_time = time.time() # Ξεκινάει η Μέτρηση χρόνου εκτέλεσης

    temp_result_routes = top_routes.take(10)

    end_time = time.time() # Τελειώνει η Μέτρηση χρόνου εκτέλεσης
    elapsed_time = end_time - start_time
    execution_times_routes.append(elapsed_time)
    print(f"Επανάληψη {i+1}: {elapsed_time:.4f} δευτερόλεπτα")


# Διαδικασία Υπολογισμου του μέσου όρου των 3 (-min, -max) μετρήσεων
times_array_routes = np.array(execution_times_routes)
times_array_routes = np.sort(times_array_routes)
trimmed_times_routes = times_array_routes[1:-1]

avg_routes_time = np.mean(trimmed_times_routes)

print(f"\nΣύνολο Μετρήσεων: {execution_times_routes}")
print(f"Αφαιρούμενες Τιμές (min/max): {times_array_routes[0]:.4f} / {times_array_routes[-1]:.4f}")
print(f"Μέσος Χρόνος Θέματος 2 (DataFrame - Trimmed Mean): {avg_routes_time:.4f} δευτερόλεπτα")

print("\n-10 routes με τη μεγαλύτερη μέση καθυστέρηση-")

top_routes.show(10)

"""4."""

#Αποθήκευση αποτελεσμάτων σε αρχείο CSV
top_10_only_df = top_routes.limit(10)
top_10_only_df.write.csv("top_10_routes", header=True, mode="overwrite")

"""# Θέμα 4:Οπτικοποίηση & Ανάλυση

1.
"""

import pandas as pd
import matplotlib.pyplot as plt

pandas_top_routes = top_routes.limit(10).toPandas()
print(f"Μέγεθος για οπτικοποίηση: {len(pandas_top_routes)} γραμμές")
print(pandas_top_routes.to_markdown(index=False))

"""2&3"""

pandas_top_routes['ROUTE'] = pandas_top_routes['ORIGIN_AIRPORT'] + '-' + pandas_top_routes['DEST_AIRPORT']
plot_df = pandas_top_routes.sort_values(by='AVG_DELAY', ascending=True)

plt.figure(figsize=(10, 6))
plt.barh(plot_df['ROUTE'], plot_df['AVG_DELAY'], color='darkred')

plt.title('Top-10 Διαδρομές με τη Μεγαλύτερη Μέση Καθυστέρηση Αναχώρησης', fontsize=14)
plt.xlabel('Μέση Καθυστέρηση (λεπτά)', fontsize=12)
plt.ylabel('Διαδρομή', fontsize=12)

for index, value in enumerate(plot_df['AVG_DELAY']):
    plt.text(value, index, f' {value:.2f}', va='center')

plt.tight_layout()
import os
os.makedirs('out', exist_ok=True)
plt.savefig('out/top_10_routes_delay.png')
plt.show()

"""# Θέμα 5: Επέκταση / Εμπλουτισμός Ανάλυσης

1a.
"""

from pyspark.sql.functions import avg, col, substring
import matplotlib.pyplot as plt

df_with_hour = df_clean.withColumn("HOUR", (col("SCHED_DEP").substr(12,2)).cast("int"))

hours_delay = df_with_hour.groupBy("HOUR") \
                              .agg(avg("DEP_DELAY").alias("AVG_DELAY")) \
                              .orderBy("HOUR")

print("-- Μέση Καθυστέρηση ανά Ώρα Αναχώρησης --")
hours_delay.show(24)

# Οπτικοποίηση: Γράφημα Γραμμής
hours_pdf = hours_delay.toPandas()

plt.figure(figsize=(12, 6))
plt.plot(hours_pdf['HOUR'], hours_pdf['AVG_DELAY'], marker='o', color='purple', linewidth=2)

plt.title('Μέση Καθυστέρηση Αναχώρησης ανά ώρα', fontsize=14)
plt.xlabel('Ώρα (0-23)', fontsize=12)
plt.ylabel('Μέση Καθυστέρηση (λεπτά)', fontsize=12)
plt.xticks(range(0, 24))
plt.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.savefig('out/hourly_delay_analysis.png')
plt.show()

"""1b."""

from pyspark.sql.functions import avg, col

# Υπολογισμός μέσης καθυστέρησης ανά Αεροπορική Εταιρεία
airline_delay_df = df_clean.groupBy("AIRLINE") \
                           .agg(avg("DEP_DELAY").alias("AVG_DELAY")) \
                           .orderBy("AVG_DELAY")

print("-- Μέση Καθυστέρηση ανά Αεροπορική Εταιρεία --")
airline_delay_df.show()

# Δημιουργία ραβδογράμματος για να συγκρίνουμε τισ επιδόσεις των εταιριών
import matplotlib.pyplot as plt
import seaborn as sns

pdf_airline = airline_delay_df.toPandas()

plt.figure(figsize=(12, 6))
bars = plt.bar(pdf_airline['AIRLINE'], pdf_airline['AVG_DELAY'], color=sns.color_palette("viridis", len(pdf_airline)))

plt.title('Μέση Καθυστέρηση Αναχώρησης ανά Αεροπορική Εταιρεία', fontsize=14)
plt.xlabel('Αεροπορική Εταιρεία (Κωδικός)', fontsize=12)
plt.ylabel('Μέση Καθυστέρηση (λεπτά)', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.1, f'{yval:.1f}', ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.savefig('out/airline_delay_analysis.png')

plt.show()

"""1c."""

df = pd.read_csv("flights_2000.csv")
df_clean = df[(df['CANCELLED'] == 0) & (df['DEP_DELAY'].notna())].copy()

# Επιλογή Top-15 Αεροδρομίων με τις περισσότερες αναχωρήσεις
top_airports = df_clean['ORIGIN_AIRPORT'].value_counts().head(15).index.tolist()
# Πτήσεις μεταξύ των 15 αεροδρομίων
df_top = df_clean[df_clean['ORIGIN_AIRPORT'].isin(top_airports) &
                  df_clean['DEST_AIRPORT'].isin(top_airports)].copy()

route_stats = df_top.groupby(['ORIGIN_AIRPORT', 'DEST_AIRPORT'])['DEP_DELAY'].mean().reset_index()

# Μετατροπή σε μορφή πίνακα (Matrix)
heatmap_data = route_stats.pivot(index='ORIGIN_AIRPORT', columns='DEST_AIRPORT', values='DEP_DELAY')

#Δημιουργία Heatmap
plt.figure(figsize=(14, 10))
sns.heatmap(heatmap_data, annot=True, fmt=".0f", cmap="coolwarm", linewidths=.5,
            cbar_kws={'label': 'Μέση Καθυστέρηση (λεπτά)'})

plt.title('Heatmap: Καθυστερήσεις ανά Διαδρομή (Top-15 Αεροδρόμια)', fontsize=16, fontweight='bold')
plt.xlabel('Αεροδρόμιο Προορισμού (Destination)', fontsize=12)
plt.ylabel('Αεροδρόμιο Αναχώρησης (Origin)', fontsize=12)

plt.tight_layout()
os.makedirs('out', exist_ok=True)
plt.savefig('out/heatmap_routes_delay.png')
plt.show()